# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

races = Race.create([
  {species: "Klingon", alignment: "Militaristic", government: "Klingon Empire" , insignia: "https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/KlingonInsignia.svg/224px-KlingonInsignia.svg.png", description:"The Klingons are a humanoid warrior species that originate from the planet Qo'noS (pronounced Kronos), an M-class planet in the Beta Quadrant. One of the major powers of the galaxy, the Klingons are a proud, tradition-bound people who value honor and combat. The aggressive Klingon culture has made them an interstellar military power to be respected and feared." },
  {species: "Human", alignment: "Discovery", government: "United Federation of Planets", insignia: "http://vignette1.wikia.nocookie.net/memoryalpha/images/b/b5/United_Federation_of_Planets_logo.svg/revision/latest/scale-to-width-down/632?cb=20101031000529&path-prefix=en", description: "The Humans (Homo sapiens), also known as Terrans, are a warp-capable humanoid species from the Alpha Quadrant. The species originated from the planet Earth in the Sol system. Humans are the only surviving race of several sentient/intelligent species to have evolved from the Genus Homo. Humans are also one of two known spacefaring intelligent species to have originated from Earth; the other being the Voth, who had come to live in the Delta Quadrant by the 24th century."},
  {species: "Borg", alignment: "Domination" , government: "Borg Collective", insignia: "https://upload.wikimedia.org/wikipedia/en/b/b2/Borg_insignia.png" , description: "The Borg are a pseudo-species of cybernetic beings, or cyborgs, from the Delta Quadrant. No single individual truly exists within the Borg Collective (with the exception of the Borg Queen), as all Borg are linked into a hive mind. Their ultimate goal was the attainment of 'perfection' through the forcible assimilation of diverse sentient species, technologies, and knowledge. As a result, the Borg are among the most powerful and feared entities in the galaxy, without really being a true species at all." },
  {species: "Ferengi", alignment: "Trade", government: "Ferengi Alliance", insignia: "http://vignette3.wikia.nocookie.net/memoryalpha/images/3/3e/Logo_Ferengi.png/revision/latest?cb=20060920184117&path-prefix=en", description: "The Ferengi are a warp-capable humanoid species from the planet Ferenginar. Ferengi civilization is built on a caricature of free enterprise, where earning profit is the sole meaningful goal in life, superseding all other endeavors."}
  ])

characters = Character.create([
  {name: "Jean Luc Picard", rank: "Captain", race_id: 2, img_url: "http://vignette1.wikia.nocookie.net/startrek/images/e/e8/Picard2379.jpg/revision/latest/scale-to-width-down/700?cb=20150223171522", bio: "Jean-Luc Picard was a 24th century Human man, born in the year 2305. He served in Starfleet and was well known throughout the Federation and beyond for his skills, intellect, command ability and having averted innumerable disasters and crises affecting individuals, starships, planets, interstellar states and the very fate of the universe."},
  {name: "Geordi La Forge", rank: "Chief Engineer", race_id: 2, img_url: "http://vignette3.wikia.nocookie.net/startrek/images/5/5b/Geordi_La_Forge_2364.jpg/revision/latest?cb=20150223173136", bio: "Geordi La Forge was a male Human who was a noted Starfleet officer and engineer who served in the 24th century. He was most famous for serving as chief engineer aboard the USS Enterprise-D and USS Enterprise-E."},
  {name: "Worf", rank: "Commander", race_id: 1, img_url: "http://vignette3.wikia.nocookie.net/startrek/images/d/dc/Lt._Jr._Worf.jpg/revision/latest/scale-to-width-down/699?cb=20120423153015", bio: "Worf, son of Mogh, of the House of Martok, (2340- ), also known as Worf Rozhenko, was one of the single most influential people in Klingon and Federation politics of the late 24th century."},
  {name: "Goss", rank: "DaiMon",  race_id: 4, img_url: "http://vignette3.wikia.nocookie.net/memoryalpha/images/7/73/Goss.jpg/revision/latest/scale-to-width-down/700?cb=20130714192954&path-prefix=en", bio: "DaiMon Goss was a 24th century Ferengi and the commanding officer of a D'Kora-class marauder. In 2366, he demanded the right to negotiate on behalf of the Ferengi for rights to the Barzan wormhole. Though he had not been invited to the proceedings by the Barzans, Premier Bhavani agreed to allow their participation."},
  {name: "Hugh", rank: "Drone", race_id: 3, img_url: "http://vignette3.wikia.nocookie.net/memoryalpha/images/4/40/Hugh-Drone.jpg/revision/latest/scale-to-width-down/700?cb=20141207193522&path-prefix=en", bio: "Hugh, formerly Third of Five, was a former Borg drone who was rescued by the USS Enterprise-D in 2368."}
  ])
